esphome:
  name: esp32-4848s040-t1
  friendly_name: ESP32-4848S040-T1
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    priority: -100
    then:
      - script.execute: inactivity_timer

preferences:
  flash_write_interval: 5s

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
    components:
      - name: "espressif/esp_websocket_client"
        ref: 1.5.0
      #- name: "espressif/esp-dsp"
      #  ref: 1.7.0
      - name: "bitbank2/jpegdec"
        source: https://github.com/strange-v/jpegdec-esphome

psram:
  mode: octal
  speed: 80MHz

external_components:
  - source: github://waxgourd-ha/RemoteWebViewClient@main
    refresh: 0s
    components: [ remote_webview ]

logger:
  hardware_uart: UART0
  level: DEBUG

api:
  id: api_id
  on_client_connected:
    - lambda: |-
        ESP_LOGD("main", "HA connected from IP: %s", client_address.c_str());

ota:
  platform: esphome

wifi:
  ap:

web_server:
  port: 80
  version: 3
  log: false

captive_portal:

improv_serial:

spi:
  clk_pin: GPIO48
  mosi_pin: GPIO47

i2c:
  - id: bus_a
    sda: GPIO19
    scl: GPIO45

display:
  - platform: st7701s
    show_test_card: False
    update_interval: never
    auto_clear_enabled: False
    spi_mode: MODE3
    data_rate: 2MHz
    color_order: RGB
    invert_colors: False
    dimensions:
      width: 480
      height: 480
    cs_pin: 39
    de_pin: 18
    hsync_pin: 16
    vsync_pin: 17
    pclk_pin: 21
    pclk_frequency: 12MHz
    pclk_inverted: False
    hsync_pulse_width: 8
    hsync_front_porch: 10
    hsync_back_porch: 20
    vsync_pulse_width: 8
    vsync_front_porch: 10
    vsync_back_porch: 10
    init_sequence:
      - 1
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10]
      - [0xCD, 0x00]
    data_pins:
      red:
        - GPIO11
        - GPIO12
        - GPIO13
        - GPIO14
        - GPIO0
      green:
        - GPIO8
        - GPIO20
        - GPIO3
        - GPIO46
        - GPIO9
        - GPIO10
      blue:
        - GPIO4
        - GPIO5
        - GPIO6
        - GPIO7
        - GPIO15

touchscreen:
  platform: gt911
  transform:
    mirror_x: false
    mirror_y: false
  on_touch:
    then:
      - script.execute: inactivity_timer

output:
  - platform: ledc
    pin: GPIO38
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON

globals:
  - id: global_saved_server_addr
    type: std::string
    restore_value: true
    initial_value: '"homeassistant.local:8081"'

remote_webview:
  id: rwv
  # ----------------------------------------------------
  # Modify server configuration: Use new server_global to point to a global variable
  server_global: global_saved_server_addr
  # server: "homeassistant.local:8081" # <-- Original line removed
  # ----------------------------------------------------
  url: id(display_target_url).state.c_str()
  full_frame_tile_count: 1
  max_bytes_per_msg: 61440
  jpeg_quality: 85

text:
  - platform: template
    name: "Display Target URL"
    id: display_target_url
    mode: TEXT
    optimistic: true
    min_length: 1
    restore_value: true
    initial_value: "http://homeassistant.local:8123"
    entity_category: "config"
    set_action:
      - lambda: |-
          if (!id(rwv).open_url(x)) {
            ESP_LOGW("rwv", "Not connected to server, URL queued: %s", x.c_str());
            id(rwv).set_url(x);
          }
          ESP_LOGI("Config", "HA URL updated to: %s", x.c_str());

  - platform: template
    name: "RemoteWebview Server Address"
    id: rwv_server_addr
    mode: TEXT
    optimistic: true
    min_length: 1
    restore_value: true
    initial_value: "homeassistant.local:8081"
    entity_category: "config"
    set_action:
      - lambda: |-
          ESP_LOGI("Config", "Server address saved: %s", x.c_str());
          // Save to global variable
          id(global_saved_server_addr) = x;
          if (!x.empty()) {
            id(rwv).set_server(x);
            ESP_LOGI("Config", "Server address updated to: %s", x.c_str());
          }
          ESP_LOGW("Config", "Restart device to ensure proper connection");

button:
  - platform: restart
    name: "esp Restart"
    entity_category: "diagnostic"

select:
  - platform: logger
    name: "Logger select"

interval:
  - interval: 5s
    then:
      - lambda: |-
          ESP_LOGD("main", "Current server address config: %s", id(rwv_server_addr).state.c_str());
          ESP_LOGD("main", "Current URL: %s", id(display_target_url).state.c_str());
          ESP_LOGD("main", "Global saved server address: %s", id(global_saved_server_addr).c_str());

script:
  - id: inactivity_timer
    mode: restart
    then:
      - if:
          condition:
            light.is_off: back_light
          then:
            - light.turn_on:
                id: back_light
            - delay: 0.5s
            - lambda: |-
                id(rwv).disable_touch(false);
      - delay: 15s
      - light.turn_off:
          id: back_light
      - lambda: |-
          id(rwv).disable_touch(true);
